func expectDestination(_ input: String, _ expected: String?) {
    let actual = InputResolver.destination(for: input)?.absoluteString
    assert(actual == expected, "\(input) → \(actual ?? "nil"), expected \(expected ?? "nil")")
}

expectDestination("github.com", "https://github.com")
expectDestination("localhost:3000", "http://localhost:3000")
expectDestination("app.test/login", "http://app.test/login")
expectDestination("https://polar.sh/pricing", "https://polar.sh/pricing")
expectDestination("swift concurrency", "https://www.google.com/search?q=swift%20concurrency")
expectDestination("hello", "https://www.google.com/search?q=hello")
expectDestination("v1.2", "https://www.google.com/search?q=v1.2")
expectDestination("   ", nil)
expectDestination("about:blank", "about:blank")
assert(SidebarViewMetrics.favoriteColumnCount(availableWidth: 194, favoriteCount: 0) == 1)
assert(SidebarViewMetrics.favoriteColumnCount(availableWidth: 194, favoriteCount: 1) == 1)
assert(SidebarViewMetrics.favoriteColumnCount(availableWidth: 194, favoriteCount: 2) == 2)
assert(SidebarViewMetrics.favoriteColumnCount(availableWidth: 194, favoriteCount: 10) == 3)
assert(SidebarViewMetrics.favoriteColumnCount(availableWidth: 444, favoriteCount: 10) == 6)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 0, targetIndex: 1) == 2)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 1, targetIndex: 0) == 0)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 8, targetIndex: 9) == 10)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 9, targetIndex: 0) == 0)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 0, targetIndex: 0) == 0)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 30, y: 22), availableWidth: 194, columnCount: 3) == 0)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 100, y: 22), availableWidth: 194, columnCount: 3) == 1)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 193, y: 122), availableWidth: 194, columnCount: 3) == 8)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: -1, y: -1), availableWidth: 194, columnCount: 3) == 0)
let favoriteIDs = (0..<10).map { _ in UUID() }
let forwardOrder = SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: favoriteIDs[0], to: 1)
assert(forwardOrder[0] == favoriteIDs[1] && forwardOrder[1] == favoriteIDs[0])
let crossPageOrder = SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: favoriteIDs[9], to: 0)
assert(crossPageOrder[0] == favoriteIDs[9] && crossPageOrder.count == favoriteIDs.count)
assert(favoriteIDs[0] != crossPageOrder[0])
assert(SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: favoriteIDs[0], to: 100).last == favoriteIDs[0])
assert(SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: UUID(), to: 0) == favoriteIDs)
print("checks passed")
