func expectDestination(_ input: String, _ expected: String?) {
    let actual = InputResolver.destination(for: input)?.absoluteString
    assert(actual == expected, "\(input) → \(actual ?? "nil"), expected \(expected ?? "nil")")
}

expectDestination("github.com", "https://github.com")
expectDestination("localhost:3000", "http://localhost:3000")
expectDestination("app.test/login", "http://app.test/login")
expectDestination("https://polar.sh/pricing", "https://polar.sh/pricing")
expectDestination("swift concurrency", "https://www.google.com/search?q=swift%20concurrency")
expectDestination("hello", "https://www.google.com/search?q=hello")
expectDestination("v1.2", "https://www.google.com/search?q=v1.2")
expectDestination("   ", nil)
expectDestination("about:blank", "about:blank")
func isClose(_ value: CGFloat, _ expected: CGFloat) -> Bool { abs(value - expected) < 0.001 }
let arcTileWidth = SidebarViewMetrics.favoriteTileWidth(availableWidth: 184)
assert(isClose(arcTileWidth, 166.0 / 3))
let middleFavorite = SidebarViewMetrics.favoritePosition(index: 4, availableWidth: 184)
assert(isClose(middleFavorite.x, arcTileWidth + 9) && isClose(middleFavorite.y, 55))
let lastFavorite = SidebarViewMetrics.favoritePosition(index: 8, availableWidth: 184)
assert(isClose(lastFavorite.x + arcTileWidth, 184))
let secondPageFavorite = SidebarViewMetrics.favoritePosition(index: 9, availableWidth: 184)
assert(isClose(secondPageFavorite.x, 184) && isClose(secondPageFavorite.y, 0))
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 0, targetIndex: 1) == 2)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 1, targetIndex: 0) == 0)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 8, targetIndex: 9) == 10)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 9, targetIndex: 0) == 0)
assert(SidebarViewMetrics.favoriteDropIndex(sourceIndex: 0, targetIndex: 0) == 0)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 30, y: 22), availableWidth: 184) == 0)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 80, y: 22), availableWidth: 184) == 1)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 80, y: 60), availableWidth: 184) == 4)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: 183, y: 300), availableWidth: 184) == 8)
assert(SidebarViewMetrics.favoriteSlot(at: CGPoint(x: -1, y: -1), availableWidth: 184) == 0)
let favoriteIDs = (0..<10).map { _ in UUID() }
let forwardOrder = SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: favoriteIDs[0], to: 1)
assert(forwardOrder[0] == favoriteIDs[1] && forwardOrder[1] == favoriteIDs[0])
let crossPageOrder = SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: favoriteIDs[9], to: 0)
assert(crossPageOrder[0] == favoriteIDs[9] && crossPageOrder.count == favoriteIDs.count)
assert(favoriteIDs[0] != crossPageOrder[0])
assert(SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: favoriteIDs[0], to: 100).last == favoriteIDs[0])
assert(SidebarViewMetrics.favoriteOrder(favoriteIDs, moving: UUID(), to: 0) == favoriteIDs)
print("checks passed")
